# cd into the uyulala folder and execute: conda env create -f condaEnv.yml
name: uyulala
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib=3.1.1
  - numpy=1.17.2
  - pandas=0.25.1
  - psutil=5.6.3
  - time
  - h2o=3.18.0
  - h2o-py
  - pip
  - pip:                            # Packages installed from PyPI
    - yfinance==0.1.54

# conda config --append channels conda-forge
# conda create --name uyulala python=3.7 matplotlib numpy pandas pip psutil time h2o h2o-py yfinance

# remove env with: conda remove --name myenv --all
# create new yml file with: conda env export --file uyulala.yml

#  - subprocess
#  - sys
#  - random
#  - os
#  - pandas_datareader
#  - string
#  - traceback
