name: uyulala
channels:
  - conda-forge
dependencies:
  - python=3.7
  - colorama=0.2.7
  - future=0.15.2
  - matplotlib=1.3.1
  - numpy=1.8.2
  - os
  - pandas=0.14.1
  - pandas_datareader
  - pip
  - psutil=2.1.1
  - random
  - requests=2.11.1
  - string
  - subprocess
  - sys
  - tabulate=0.7.5
  - time
  - traceback
  - pip:                            # Packages installed from PyPI
    - http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o

# conda config --append channels conda-forge
# conda create --name uyulala python=3.7 matplotlib numpy pandas pip psutil time h2o h2o-py yfinance

#  - subprocess
#  - sys
#  - random
#  - os
#  - pandas_datareader
#  - string
#  - traceback
